[project]
name = "rctl-bot"
version = "0.1.0"
description = "Stolyarchuk AI Bot"
readme = "README.md"
authors = [
    { name = "Roman Stolyarchuk", email = "roman@stolyarch.uk" }
]
requires-python = ">=3.13"
dependencies = [
    "aiogram==3.30.0",
    "pydantic-settings>=2,<3",
    "python-dotenv>=1,<2",
    "uvloop>=0.22.1",
]

[dependency-groups]
dev = [
    "pytest>=8,<9",
]

[tool.pytest.ini_options]
pythonpath = ["."]
